### ISSUE TITLE
Latest Version syntaxErrot

### ISSUE THREAD

**Issue by LiuXiaoJie** [felixrieseberg/ember-cli-windows#22]
I update this through npm today. When run the command 'ember-cli-windows', get the error as below:
C:\Program Files\nodejs\node_modules\ember-cli-windows\bin\ember-cli-windows:196

.then(executeConfiguration);
^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Then i check the 'bin\ember-cli-windows', is it the ';' should not appear in the end of line 195?

**Comment by felixrieseberg** [comment]
Oh man, how embarrassing. Thanks for alerting me - this is now fixed.
